name: Bridgecord
version: 1.0
author: moderator_man
main: net.oldschoolminecraft.bcord.Bridgecord
depend:
  - DiscordCore
softdepend: [AuthMe, xAuth, OSAS, JoinsPlus, Invisiman]
commands:
  dlink:
    description: Link your Discord account to your in-game account. It's cool!