name: Bridgecord
version: 1.4
author: moderator_man
main: net.oldschoolminecraft.bcord.Bridgecord
depend: [DiscordCore]
softdepend: [AuthMe, xAuth, OSAS, JoinsPlus, Invisiman]
commands:
  dlink:
    description: Link your Discord account to your in-game account. It's cool!
  bcord:
    description: View version info & reload config
    default: op
    permission: bcord.admin
dependencies: #-- UNCOMMENT THESE LINES IF YOU ARE NOT COMPILING WITH SHADOW
  - 'com.mysql:mysql-connector-j:8.2.0'
#  - 'commons-logging:commons-logging:1.3.2'
#  - 'org.apache.commons:commons-pool2:2.12.0'
#  - 'org.apache.commons:commons-dbcp2:2.12.0'